vich_uploader:
    db_driver: orm

    metadata:
       type: attribute

    mappings:
       vehicle_images:
           uri_prefix: /images/vehicle
           upload_destination: '%kernel.project_dir%/public/images/vehicle'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       verification_documents:
           uri_prefix: /documents/seller
           upload_destination: '%kernel.project_dir%/public/documents/seller'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       logo_images:
           uri_prefix: /images/seller
           upload_destination: '%kernel.project_dir%/public/images/seller'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
